
# Use the official Nginx image
FROM nginx:1.29-alpine

# Remove the default config
RUN rm /etc/nginx/conf.d/default.conf

# Copy custom Nginx configuration and supporting files
COPY nginx.conf /etc/nginx/nginx.conf
COPY mime.types /etc/nginx/mime.types
COPY snippets /etc/nginx/snippets
COPY http.d /etc/nginx/http.d
COPY error_pages /etc/nginx/error_pages
COPY certs /etc/nginx/certs

# Expose HTTP and HTTPS ports
EXPOSE 80 443

# Start Nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]
